### ISSUE TITLE
Broken super strict on precision/scale policy

### ISSUE THREAD

**Issue by DannyMeyer** [php-collective/decimal-object#13]
With every calculation operation where $scale can be provided, the super strict on precision/scale policy is beeing softened.

For example:
```php
$decimal = new Decimal('123.123456');
$value = $decimal->add(0, 2);
var_dump($value->toString());
```

will result in
```
string(6) "123.12"
```
With the strict policy i would expect the `InvalidArgumentException` with the message: `Loss of precision detected. Detected scale `6` > `2` as defined.`

**Comment by dereuromark** [comment]
You are providing scale here as 2nd param, wouldnt that mean u want to set 2 as (min) scale here?

**Comment by InvisibleSmiley** [comment]
The documentation states:
> Operations like add() use the higher of the scales of the operands.

So I would expect to have 2 be applied to 0 (resulting in 0.00) and 123.123456 to be the result.

**Comment by InvisibleSmiley** [comment]
I guess some of the confusion stems from the fact that this lib uses bcmath internally (in this case bcadd) the operation of which is well-documented (https://www.php.net/manual/en/function.bcadd.php), while the API of this lib does not describe in detail what the parameters do (neither via PHPDoc nor Markdown documentation) right now.

I guess the first question to ask is what the lib methods are *supposed* to do, and IMHO that should ideally be self-explanatory rather than depending on people's expectations (which as we can see here vary). Then adapt the implementation, then the documentation.

**Comment by dereuromark** [comment]
A PR is welcome to clarify further
https://github.com/php-collective/decimal-object/tree/master/docs#precisionscale
states the basics so far afaik.
